# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Code Coverage

on: [push, workflow_dispatch, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rails-version: ["6.1", "7.1"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install dependencies
        run: bundle install
        env:
          TEST_RAILS_VERSION: ${{ matrix.rails-version }}
          DEBUG: true
      - name: Run tests
        run: bundle exec rake
  lint:
    runs-on: ubuntu-20.04
    permissions:
      checks: write
      contents: write
    steps:
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@v1
